# Generated by Django 5.0.14 on 2026-02-17 00:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='waterintakesettings',
            name='goal_unit',
            field=models.CharField(choices=[('ml', 'Milliliters'), ('oz', 'Ounces')], default='ml', max_length=2),
        ),
        migrations.AddField(
            model_name='waterintakesettings',
            name='smart_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='waterintakesettings',
            name='weather_adjustment_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waterintakesettings',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=10),
        ),
        migrations.AddField(
            model_name='waterintakesettings',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='WaterContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('volume_ml', models.PositiveIntegerField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_containers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_favorite', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='waterlog',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='health.watercontainer'),
        ),
    ]
