# Generated by Django 5.0.14 on 2026-02-18 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_populate_exercise_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='exerciseset',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AlterModelOptions(
            name='exercisestats',
            options={'verbose_name_plural': 'Exercise Stats'},
        ),
        migrations.AlterModelOptions(
            name='fitnessgoal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fitness Goal'},
        ),
        migrations.AlterModelOptions(
            name='musclegroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='personalrecord',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='progressiveoverload',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='restday',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workout'},
        ),
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='workoutlog',
            options={'ordering': ['-date', '-start_time']},
        ),
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workout Plan'},
        ),
        migrations.AlterModelOptions(
            name='workoutplanday',
            options={'ordering': ['day_of_week']},
        ),
        migrations.AlterModelOptions(
            name='workoutplanweek',
            options={'ordering': ['week_number']},
        ),
        migrations.RenameIndex(
            model_name='sleeplog',
            new_name='health_slee_user_id_bf6a8f_idx',
            old_name='health_slee_user__date_idx',
        ),
        migrations.RenameIndex(
            model_name='sleeplog',
            new_name='health_slee_user_id_5c3f18_idx',
            old_name='health_slee_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='sleeplog',
            new_name='health_slee_quality_82659b_idx',
            old_name='health_slee_quality_idx',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, help_text='Step-by-step instructions'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='is_compound',
            field=models.BooleanField(default=False, help_text='Multi-joint exercise'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='is_isolation',
            field=models.BooleanField(default=False, help_text='Single-joint exercise'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Pre-built system exercise'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='rpe',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rate of Perceived Exertion (1-10)', null=True),
        ),
        migrations.AlterField(
            model_name='fitnessgoal',
            name='milestones',
            field=models.JSONField(blank=True, default=list, help_text='List of milestone values'),
        ),
        migrations.AlterField(
            model_name='fitnessgoal',
            name='target_strength_value',
            field=models.CharField(blank=True, help_text="e.g., 'Bench Press 100kg'", max_length=100),
        ),
        migrations.AlterField(
            model_name='fitnessgoal',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit of measurement', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False if beaten by a newer record'),
        ),
        migrations.AlterField(
            model_name='restday',
            name='energy_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-10 energy level', null=True),
        ),
        migrations.AlterField(
            model_name='restday',
            name='muscle_soreness',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-10 soreness level', null=True),
        ),
        migrations.AlterField(
            model_name='sleepinsight',
            name='related_sleep_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.sleeplog'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='is_template',
            field=models.BooleanField(default=False, help_text='If True, this is a reusable template'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags for filtering'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='distance_m',
            field=models.PositiveIntegerField(blank=True, help_text='For cardio exercises', null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='For cardio/timed exercises', null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order within the workout'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='rep_range',
            field=models.CharField(blank=True, help_text="e.g., '8-12'", max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='reps',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Reps per set', null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='rest_seconds',
            field=models.PositiveSmallIntegerField(default=60, help_text='Rest time after this exercise'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='sets',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of sets', null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='mood_after',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-10 after workout', null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='mood_before',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-10 before workout', null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='total_volume_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total weight lifted', max_digits=10),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='weeks',
            field=models.PositiveSmallIntegerField(help_text='Number of weeks in the plan'),
        ),
        migrations.AlterField(
            model_name='workoutplanweek',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_weeks', to='health.workoutplan'),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='workoutlog',
            index=models.Index(fields=['user', '-date'], name='health_work_user_id_f62835_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutlog',
            index=models.Index(fields=['date'], name='health_work_date_4a1031_idx'),
        ),
    ]
