# Generated by Django 5.0.14 on 2026-02-18 03:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
        ('habits', '0001_initial'),
        ('pomodoro', '0002_pomodorosession_day_of_week_and_more'),
        ('tasks', '0002_task_enhancements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarviewpreference',
            options={'verbose_name_plural': 'Calendar View Preferences'},
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='attendees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='has_conflict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='linked_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='habits.habit'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='linked_pomodoro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='pomodoro.pomodorosession'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='priority',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('tentative', 'Tentative'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='time_block_type',
            field=models.CharField(blank=True, choices=[('deep_work', 'Deep Work'), ('meeting', 'Meeting'), ('break', 'Break'), ('buffer', 'Buffer Time'), ('focus', 'Focus Time'), ('review', 'Review')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calendarviewpreference',
            name='active_calendars',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calendarviewpreference',
            name='active_event_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calendarviewpreference',
            name='hour_end',
            field=models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='calendarviewpreference',
            name='hour_start',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='calendarviewpreference',
            name='show_pomodoro',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('event', 'Event'), ('meeting', 'Meeting'), ('appointment', 'Appointment'), ('deadline', 'Deadline'), ('time_block', 'Time Block'), ('task', 'Task'), ('habit', 'Habit'), ('reminder', 'Reminder'), ('pomodoro', 'Pomodoro Session')], default='event', max_length=20),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='linked_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='calendarviewpreference',
            name='default_view',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year'), ('agenda', 'Agenda')], default='week', max_length=20),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('calendar_type', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('family', 'Family'), ('project', 'Project'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Calendars',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='calendar.calendar'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'start_date'], name='calendar_ca_user_id_22d369_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'start_date', 'end_date'], name='calendar_ca_user_id_8aa432_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['calendar'], name='calendar_ca_calenda_ff319e_idx'),
        ),
    ]
