# Generated by Django on 2026-02-16

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(blank=True, max_length=50)),
                (
                    'asset_type',
                    models.CharField(
                        choices=[
                            ('stock', 'Stock'),
                            ('fund', 'Fund'),
                            ('crypto', 'Crypto'),
                            ('bond', 'Bond'),
                            ('cash', 'Cash'),
                            ('other', 'Other'),
                        ],
                        default='stock',
                        max_length=20,
                    ),
                ),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16)),
                ('cost_basis', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                (
                    'account',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='investments',
                        to='finance.account',
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_holdings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('assets', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('liabilities', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('net_worth', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                (
                    'user',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_worth_snapshots', to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='income_source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='transactions',
                to='finance.incomesource',
            ),
        ),
    ]
