# Generated by Django 5.0.14 on 2026-02-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_attachments_templates_links_analytics'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_note_user_id_d67ab6_idx',
            old_name='notes_note_user_id_9af683_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_note_user_id_d0efd6_idx',
            old_name='notes_note_user_id_ee9d2e_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_note_user_id_033aa6_idx',
            old_name='notes_note_user_id_6356fd_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_note_note_ty_def091_idx',
            old_name='notes_note_note_ty_f847fb_idx',
        ),
    ]
