# Generated by Django 5.0.14 on 2026-02-14 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_duration', models.PositiveIntegerField(default=25)),
                ('short_break', models.PositiveIntegerField(default=5)),
                ('long_break', models.PositiveIntegerField(default=15)),
                ('auto_start_breaks', models.BooleanField(default=False)),
                ('auto_start_work', models.BooleanField(default=False)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pomodoro_settings',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'session_type',
                    models.CharField(
                        choices=[('work', 'Work'), ('short_break', 'Short Break'), ('long_break', 'Long Break')],
                        default='work',
                        max_length=20,
                    ),
                ),
                ('duration', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('interruptions', models.PositiveIntegerField(default=0)),
                (
                    'task',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='tasks.task',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pomodoro_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
