# Generated by Django 5.0.14 on 2026-02-14 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
        ('tasks', '0002_task_enhancements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosession',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='energy_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Energy level during session 1-5', null=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='hour_of_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='productivity_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Self-rated productivity 1-10', null=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomodoro_sessions', to='tasks.project'),
        ),
        migrations.AddField(
            model_name='pomodorosettings',
            name='break_enforcement_delay',
            field=models.PositiveIntegerField(default=5, help_text='Minutes to delay before allowing skip'),
        ),
        migrations.AddField(
            model_name='pomodorosettings',
            name='daily_pomodoro_goal',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='pomodorosettings',
            name='enable_break_enforcement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pomodorosettings',
            name='enable_desktop_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pomodorosettings',
            name='enable_sound_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pomodorosettings',
            name='long_break_interval',
            field=models.PositiveIntegerField(default=4, help_text='Sessions before long break'),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomodoro_sessions', to='tasks.task'),
        ),
        migrations.CreateModel(
            name='DeepWorkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('pomodoro_count', models.PositiveIntegerField(default=0)),
                ('total_focus_minutes', models.PositiveIntegerField(default=0)),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('productivity_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deep_work_sessions', to='tasks.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deep_work_sessions', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deep_work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DistractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distraction_type', models.CharField(choices=[('notification', 'Notification'), ('conversation', 'Conversation'), ('environmental', 'Environmental'), ('physical', 'Physical'), ('mental', 'Mental'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recovered', models.BooleanField(default=False, help_text='Whether user returned to focus')),
                ('recovery_time_seconds', models.PositiveIntegerField(blank=True, help_text='Time to return to focus', null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distractions', to='pomodoro.pomodorosession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distraction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FocusStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak_date', models.DateField(blank=True, null=True)),
                ('last_session_date', models.DateField(blank=True, null=True)),
                ('sessions_today', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_focus_minutes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='focus_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
