# Generated by Django 5.0.14 on 2026-02-18 03:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        ('journal', '0001_initial'),
        ('tasks', '0002_task_enhancements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mood_value', models.IntegerField(help_text='The numeric mood rating')),
                ('time_of_day', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('anytime', 'Anytime')], default='anytime', max_length=20)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('entry_time', models.TimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('weather', models.CharField(blank=True, help_text="e.g., 'Sunny', 'Rainy'", max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_emotion', models.CharField(choices=[('joy', 'Joy'), ('sadness', 'Sadness'), ('anger', 'Anger'), ('fear', 'Fear'), ('disgust', 'Disgust'), ('surprise', 'Surprise'), ('trust', 'Trust'), ('anticipation', 'Anticipation'), ('love', 'Love'), ('optimism', 'Optimism'), ('submission', 'Submission'), ('awe', 'Awe'), ('disapproval', 'Disapproval'), ('remorse', 'Remorse'), ('contempt', 'Contempt'), ('aggressiveness', 'Aggressiveness')], max_length=20)),
                ('specific_emotion', models.CharField(blank=True, max_length=50)),
                ('intensity', models.PositiveSmallIntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Strong'), (4, 'Intense')], default=2)),
                ('is_dominant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mood_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='mood.moodentry')),
            ],
            options={
                'ordering': ['-is_dominant', '-intensity'],
            },
        ),
        migrations.CreateModel(
            name='MoodFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('sleep', 'Sleep'), ('exercise', 'Exercise'), ('social', 'Social Interaction'), ('work', 'Work Stress'), ('diet', 'Diet/Nutrition'), ('weather', 'Weather'), ('health', 'Physical Health'), ('productivity', 'Productivity'), ('relationships', 'Relationships'), ('finances', 'Finances'), ('hobbies', 'Hobbies/Leisure'), ('environment', 'Environment'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(blank=True, help_text="Specific factor name (e.g., 'Morning Run')", max_length=100)),
                ('impact', models.SmallIntegerField(help_text='Impact on mood: -5 (very negative) to +5 (very positive)')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Quality rating 1-10', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mood_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='mood.moodentry')),
            ],
            options={
                'ordering': ['category', '-impact'],
            },
        ),
        migrations.CreateModel(
            name='MoodInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('pattern', 'Pattern Detection'), ('suggestion', 'Improvement Suggestion'), ('warning', 'Mood Warning'), ('achievement', 'Positive Achievement'), ('correlation', 'Correlation Discovery'), ('prediction', 'Mood Prediction')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mood.moodentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('scale_type', models.CharField(choices=[('numeric', 'Numeric (1-10)'), ('emoji', 'Emoji-based'), ('descriptive', 'Descriptive Words')], default='numeric', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('min_value', models.IntegerField(default=1)),
                ('max_value', models.IntegerField(default=10)),
                ('scale_labels', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_scales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='moodentry',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='mood.moodscale'),
        ),
        migrations.CreateModel(
            name='MoodStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_entries', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('avg_mood_7d', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('avg_mood_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('avg_mood_90d', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mood_distribution', models.JSONField(blank=True, default=dict)),
                ('time_of_day_averages', models.JSONField(blank=True, default=dict)),
                ('day_of_week_averages', models.JSONField(blank=True, default=dict)),
                ('best_mood_date', models.DateField(blank=True, null=True)),
                ('worst_mood_date', models.DateField(blank=True, null=True)),
                ('top_emotions', models.JSONField(blank=True, default=list)),
                ('top_positive_factors', models.JSONField(blank=True, default=list)),
                ('top_negative_factors', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mood_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mood Stats',
            },
        ),
        migrations.CreateModel(
            name='MoodTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('event', 'Specific Event'), ('person', 'Interaction with Person'), ('thought', 'Thought/Memory'), ('physical', 'Physical Sensation'), ('external', 'External Circumstance'), ('internal', 'Internal State')], max_length=20)),
                ('description', models.TextField(help_text='Description of what triggered this mood')),
                ('is_positive', models.BooleanField(default=True, help_text='True if positive trigger, False if negative')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mood_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='mood.moodentry')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodCorrelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_type', models.CharField(choices=[('sleep', 'Sleep Quality'), ('exercise', 'Exercise'), ('habits', 'Habit Completion'), ('productivity', 'Productivity'), ('social', 'Social Activity'), ('work', 'Work Activity'), ('weather', 'Weather')], max_length=20)),
                ('coefficient', models.DecimalField(decimal_places=3, max_digits=4)),
                ('strength', models.CharField(choices=[('very_strong_positive', 'Very Strong Positive'), ('strong_positive', 'Strong Positive'), ('moderate_positive', 'Moderate Positive'), ('weak_positive', 'Weak Positive'), ('none', 'No Correlation'), ('weak_negative', 'Weak Negative'), ('moderate_negative', 'Moderate Negative'), ('strong_negative', 'Strong Negative'), ('very_strong_negative', 'Very Strong Negative')], default='none', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('data_points', models.PositiveIntegerField(default=0)),
                ('insights', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_correlations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-computed_at'],
                'unique_together': {('user', 'correlation_type', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='MoodJournalLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_themes', models.JSONField(blank=True, default=list)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_link', to='journal.journalentry')),
                ('mood_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_link', to='mood.moodentry')),
            ],
            options={
                'unique_together': {('mood_entry', 'journal_entry')},
            },
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['user', '-entry_date', '-entry_time'], name='mood_mooden_user_id_aef3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['user', 'time_of_day'], name='mood_mooden_user_id_1e0617_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['mood_value'], name='mood_mooden_mood_va_efcbed_idx'),
        ),
    ]
