# Generated by Django 5.0.14 on 2026-02-18 03:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('rendered_content', models.TextField(blank=True, help_text='HTML rendered from markdown')),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('sentence_count', models.PositiveIntegerField(default=0)),
                ('paragraph_count', models.PositiveIntegerField(default=0)),
                ('sentiment_score', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('reading_time_minutes', models.PositiveIntegerField(default=1)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('edit_count', models.PositiveIntegerField(default=0)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='journal.journalentry')),
            ],
            options={
                'verbose_name_plural': 'Entry Analytics',
            },
        ),
        migrations.CreateModel(
            name='JournalMood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mood', models.PositiveSmallIntegerField(choices=[(5, 'Amazing'), (4, 'Good'), (3, 'Okay'), (2, 'Bad'), (1, 'Terrible')])),
                ('energy_level', models.PositiveSmallIntegerField(blank=True, help_text='1-10', null=True)),
                ('stress_level', models.PositiveSmallIntegerField(blank=True, help_text='1-10', null=True)),
                ('sleep_quality', models.PositiveSmallIntegerField(blank=True, help_text='1-10', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_moods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='journal.journalmood'),
        ),
        migrations.CreateModel(
            name='JournalPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('prompt_type', models.CharField(choices=[('reflection', 'Daily Reflection'), ('gratitude', 'Gratitude'), ('goal', 'Goal Review'), ('creativity', 'Creative Writing'), ('mindfulness', 'Mindfulness')], max_length=20)),
                ('question', models.TextField(help_text='The prompt/question for the user')),
                ('suggestions', models.TextField(blank=True, help_text='Suggested answers or starter phrases')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, help_text='1-5 difficulty level')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prompt_type', 'difficulty', 'question'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='journal.journalprompt'),
        ),
        migrations.CreateModel(
            name='JournalReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('next_reminder_date', models.DateField(db_index=True)),
                ('highlight_excerpt', models.TextField(blank=True, help_text='Highlighted text from the entry')),
                ('reflection_question', models.TextField(blank=True, help_text='Question to prompt reflection')),
                ('is_sent', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='journal.journalentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('total_entries', models.PositiveIntegerField(default=0)),
                ('total_word_count', models.PositiveIntegerField(default=0)),
                ('avg_word_count', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('avg_mood', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('mood_distribution', models.JSONField(blank=True, default=dict)),
                ('most_used_tags', models.JSONField(blank=True, default=list)),
                ('entries_this_week', models.PositiveIntegerField(default=0)),
                ('entries_this_month', models.PositiveIntegerField(default=0)),
                ('entries_this_year', models.PositiveIntegerField(default=0)),
                ('most_productive_day', models.CharField(blank=True, max_length=10)),
                ('avg_entries_per_week', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Journal Stats',
            },
        ),
        migrations.CreateModel(
            name='JournalStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('last_entry_date', models.DateField(blank=True, null=True)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('best_streak_start', models.DateField(blank=True, null=True)),
                ('best_streak_end', models.DateField(blank=True, null=True)),
                ('total_entries', models.PositiveIntegerField(default=0)),
                ('total_word_count', models.PositiveIntegerField(default=0)),
                ('longest_streak_this_month', models.PositiveIntegerField(default=0)),
                ('longest_streak_this_year', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Streak',
            },
        ),
        migrations.CreateModel(
            name='JournalTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='journalprompt',
            name='tags',
            field=models.ManyToManyField(blank=True, to='journal.journaltag'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='journal.journaltag'),
        ),
        migrations.CreateModel(
            name='JournalTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('morning', 'Morning Pages'), ('evening', 'Evening Reflection'), ('weekly', 'Weekly Review'), ('monthly', 'Monthly Review'), ('gratitude', 'Gratitude Journal'), ('goal', 'Goal Setting'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='book', max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('content', models.TextField(help_text='Template content with {{prompt}} placeholders')),
                ('suggest_mood', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_tags', models.ManyToManyField(blank=True, related_name='template_defaults', to='journal.journaltag')),
                ('prompts', models.ManyToManyField(blank=True, to='journal.journalprompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='journal.journaltemplate'),
        ),
        migrations.AddIndex(
            model_name='journalmood',
            index=models.Index(fields=['user', '-date'], name='journal_jou_user_id_377f35_idx'),
        ),
        migrations.AddIndex(
            model_name='journalmood',
            index=models.Index(fields=['mood'], name='journal_jou_mood_5c5254_idx'),
        ),
        migrations.AddIndex(
            model_name='journalreminder',
            index=models.Index(fields=['user', 'next_reminder_date'], name='journal_jou_user_id_fc940d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalreminder',
            index=models.Index(fields=['is_sent'], name='journal_jou_is_sent_491217_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journaltag',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='journalprompt',
            index=models.Index(fields=['prompt_type'], name='journal_jou_prompt__be1d67_idx'),
        ),
        migrations.AddIndex(
            model_name='journalprompt',
            index=models.Index(fields=['difficulty'], name='journal_jou_difficu_e690f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journaltemplate',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', '-entry_date'], name='journal_jou_user_id_840c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'is_favorite'], name='journal_jou_user_id_a2ab11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('user', 'entry_date')},
        ),
    ]
